logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "revanced ReVanced"
version = "30.8.4"
included-patches = "'Remove screen capture restriction' 'Remove screenshot restriction' 'Override certificate pinning' 'Settings' 'Fix Google login' 'Disable login requirement' 'Hide ads' 'Show seekbar' 'Downloads' 'Playback speed' 'Feed filter'"
